#Movie Recommender System

#Import CSV and Required Libraries

In [124]:
import pandas as pd 
import numpy as np
import warnings

warnings.filterwarnings( 'ignore' )

In [125]:
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)

In [126]:
#csv data import
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv('tmdb_5000_credits.csv')

In [127]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [128]:

credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

#We hava to data set so firslty we can merge both data set based on 'id' or 'title'

In [129]:
#let's merge both data sets
movies = movies.merge(credits, on='title')

In [130]:
movies.shape

(4809, 23)

In [131]:
movies = movies.head(1000)

#extract important features
- genres 
- id
- keywords
- title
- overview
- genres
- cast
- crew

In [132]:
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords',  'cast', 'crew']]
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [133]:
#check missing values
movies.isna().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [134]:
movies.dropna(inplace=True)
movies.isna().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [135]:
#lets check duplicate values
movies.duplicated().sum()

np.int64(0)

In [136]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [137]:
#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#we need this form : ['Action', 'Adventure', 'Fantasy', 'Science Fiction']
# if now we will try to call covert fucntion it will throw error bcz data is in string so first have to convert it into list

import ast

def convert(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [138]:
movies['genres'] = movies.genres.apply(convert)
movies['keywords'] = movies.keywords.apply(convert)

In [139]:
import ast

def convert3(obj):
    l = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            l.append(i['name'])
            counter += 1
        else:
            break
    return l

In [140]:

movies['cast'] = movies.cast.apply(convert3)
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [141]:
import ast

def fetch_director(obj):
    l = []
    for i in ast.literal_eval(obj):
       if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l

In [142]:

movies['crew'] = movies.crew.apply(fetch_director)
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [143]:
movies.overview[0]

#this is in string

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [144]:
#lets convet into list
movies['overview'] = movies.overview.apply(lambda x : x.split())
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [145]:
def remove_spaces(x):
    return [i.replace(" ", "") for i in x]

In [146]:
movies ['genres'] = movies.genres.apply(remove_spaces)
movies ['keywords'] = movies.keywords.apply(remove_spaces)
movies ['cast'] = movies.cast.apply(remove_spaces)
movies ['crew'] = movies.crew.apply(remove_spaces)

In [147]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]

#Now will create new column : tags

In [148]:
movies['tags'] = movies['overview'] = movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction, c..."

In [149]:
new_df = movies[['movie_id', 'title', 'tags']]
new_df.head(1)

   movie_id   title                                               tags
0     19995  Avatar  [Action, Adventure, Fantasy, ScienceFiction, c...

In [150]:
#Lets convet into string

new_df['tags'] = new_df['tags'].apply(lambda x :" ".join(x))

In [151]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,Action Adventure Fantasy ScienceFiction cultur...
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drugabuse exoti...
2,206647,Spectre,Action Adventure Crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,Action Crime Drama Thriller dccomics crimefigh...
4,49529,John Carter,Action Adventure ScienceFiction basedonnovel m...

In [152]:
#lets convert into lower case


new_df['tags'] = new_df.tags.apply(lambda x : x.lower())
new_df.head()

,movie_id,title,tags
0,19995,Avatar,action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,206647,Spectre,action adventure crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...
4,49529,John Carter,action adventure sciencefiction basedonnovel m...

In [153]:
# we will merger similar words : ['love', 'loveing', 'loved'] = ['love', 'love', 'love']
# Step 1: Install nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [154]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [155]:
new_df['tags'] = new_df.tags.apply(stem)
new_df.tags

0      action adventur fantasi sciencefict culturecla...
1      adventur fantasi action ocean drugabus exotici...
2      action adventur crime spi basedonnovel secreta...
3      action crime drama thriller dccomic crimefight...
4      action adventur sciencefict basedonnovel mar m...
                             ...
995    action thriller sciencefict dystopia mindcontr...
996    fantasi drama romanc civilwar southernusa magi...
997    comedi crime drama thriller corrupt moder tvsh...
998    comedi stupid sequel fashion malemodel fashion...
999    comedi crime hotel robberi basedonnovel judg h...
Name: tags, Length: 1000, dtype: object

### Now question is this, how we can make  model that can suggest similar  movies based on uses's search ,

#we have textual data , we will convert this into vector form 
- why : we will convert it into vector : bcz we have 5000 movies data so when we will  convert it into vector so there will be 5000k vector , and assume we search a movie that vector position is 'x' now we want to suggest similer movies , how we can suggest we will find the nearest vector of 'x' will show that simple.
- we will use bag of words techninqu,
- In bag of words we combine all tags words ,then we finde most commen words exp: a tag is salman khan so will check how many times salman khan word comes
-In vectorization we will not consider stop words : are, is, if , from, to, etc..
- after convert vector will find cosin distacne b/w each moviese

In [156]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

In [157]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [158]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1000, 5000))

In [159]:
len(cv.get_feature_names_out())

5000

In [160]:
#cosin distance

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [161]:
similarity[1] #for distance from the first movie to fist movie

array([0.11785113, 1.        , 0.1132277 , 0.0379049 , 0.08703883,
       0.20833333, 0.        , 0.10206207, 0.10910895, 0.15309311,
       0.14433757, 0.11785113, 0.57906602, 0.19802951, 0.14852213,
       0.09365858, 0.14852213, 0.34050261, 0.05661385, 0.13693064,
       0.14048787, 0.10910895, 0.1132277 , 0.10540926, 0.19802951,
       0.08333333, 0.14433757, 0.11572751, 0.08333333, 0.09622504,
       0.24056261, 0.13363062, 0.20412415, 0.15811388, 0.05270463,
       0.10206207, 0.1132277 , 0.10206207, 0.15811388, 0.10206207,
       0.05103104, 0.09901475, 0.        , 0.04682929, 0.05892557,
       0.05455447, 0.19245009, 0.10206207, 0.13608276, 0.        ,
       0.16984156, 0.10910895, 0.14433757, 0.08703883, 0.05103104,
       0.15713484, 0.12309149, 0.        , 0.06804138, 0.09901475,
       0.        , 0.16984156, 0.12909944, 0.08908708, 0.05270463,
       0.03928371, 0.04950738, 0.06154575, 0.14433757, 0.04454354,
       0.1132277 , 0.23145502, 0.14852213, 0.04682929, 0.05270463,
       0.1767767 , 0.08512565, 0.        , 0.08703883, 0.16366342,
       0.09128709, 0.14852213, 0.04256283, 0.15430335, 0.14852213,
       0.13693064, 0.12309149, 0.05270463, 0.13055824, 0.08164966,
       0.09622504, 0.13608276, 0.12009612, 0.04454354, 0.19245009,
       0.0335578 , 0.09901475, 0.1132277 , 0.11785113, 0.09901475,
       0.05455447, 0.09901475, 0.16984156, 0.16329932, 0.17817416,
       0.1132277 , 0.17766726, 0.13055824, 0.09365858, 0.10206207,
       0.        , 0.09901475, 0.09365858, 0.08512565, 0.08703883,
       0.18257419, 0.04811252, 0.14433757, 0.0379049 , 0.03402069,
       0.        , 0.16984156, 0.15309311, 0.06299408, 0.08512565,
       0.06900656, 0.19802951, 0.09128709, 0.        , 0.17817416,
       0.04950738, 0.19364917, 0.05270463, 0.09128709, 0.10910895,
       0.        , 0.10206207, 0.        , 0.13693064, 0.09563651,
       0.06454972, 0.05270463, 0.10540926, 0.16366342, 0.0372678 ,
       0.08006408, 0.        , 0.12309149, 0.12309149, 0.08164966,
       0.08908708, 0.08703883, 0.09128709, 0.10910895, 0.05455447,
       0.        , 0.03311331, 0.11785113, 0.08703883, 0.10206207,
       0.13363062, 0.04811252, 0.14433757, 0.04351941, 0.11785113,
       0.035007  , 0.08908708, 0.12909944, 0.14852213, 0.13363062,
       0.11785113, 0.06454972, 0.08512565, 0.06154575, 0.09128709,
       0.10206207, 0.04166667, 0.        , 0.14433757, 0.06154575,
       0.035007  , 0.10998534, 0.16366342, 0.10825318, 0.05455447,
       0.05270463, 0.06900656, 0.21821789, 0.04003204, 0.06454972,
       0.10206207, 0.16666667, 0.05455447, 0.14433757, 0.        ,
       0.1132277 , 0.04082483, 0.09622504, 0.10540926, 0.44907312,
       0.04454354, 0.        , 0.05892557, 0.1132277 , 0.04256283,
       0.12309149, 0.13693064, 0.08703883, 0.16984156, 0.04454354,
       0.09901475, 0.05892557, 0.07216878, 0.07715167, 0.        ,
       0.10502101, 0.21081851, 0.10540926, 0.06804138, 0.12909944,
       0.09365858, 0.05103104, 0.06154575, 0.06154575, 0.05661385,
       0.05270463, 0.05892557, 0.04682929, 0.10910895, 0.09622504,
       0.08703883, 0.        , 0.14852213, 0.1132277 , 0.13363062,
       0.09622504, 0.05103104, 0.11785113, 0.125     , 0.        ,
       0.07715167, 0.16984156, 0.09365858, 0.125     , 0.05270463,
       0.08333333, 0.04256283, 0.        , 0.04256283, 0.05270463,
       0.        , 0.        , 0.04351941, 0.05661385, 0.08908708,
       0.        , 0.05892557, 0.05455447, 0.05661385, 0.1132277 ,
       0.09128709, 0.0372678 , 0.12247449, 0.10910895, 0.        ,
       0.05455447, 0.04682929, 0.14852213, 0.04682929, 0.        ,
       0.04454354, 0.18731716, 0.        , 0.03928371, 0.08333333,
       0.04682929, 0.14048787, 0.10206207, 0.09128709, 0.04454354,
       0.05661385, 0.04003204, 0.04811252, 0.05892557, 0.        ,
       0.10206207, 0.0745356 , 0.04003204, 0.        , 0.10540926,
       0.10540926, 0.1132277 , 0.16984156, 0.04950738, 0.1767767 ,
       0.10910895, 0.06900656, 0.04454354, 0.        , 0.08006408,
       0.08908708, 0.        , 0.13608276, 0.05103104, 0.11785113,
       0.07856742, 0.06154575, 0.10540926, 0.05892557, 0.13608276,
       0.18330889, 0.05661385, 0.12909944, 0.        , 0.        ,
       0.19364917, 0.04564355, 0.        , 0.        , 0.06804138,
       0.05661385, 0.        , 0.10998534, 0.        , 0.06154575,
       0.04950738, 0.04811252, 0.09622504, 0.05103104, 0.12768848,
       0.125     , 0.1132277 , 0.15309311, 0.04256283, 0.14048787,
       0.04811252, 0.09901475, 0.05661385, 0.        , 0.09365858,
       0.29462783, 0.10910895, 0.08908708, 0.        , 0.07715167,
       0.06804138, 0.        , 0.        , 0.05103104, 0.08006408,
       0.1132277 , 0.        , 0.05270463, 0.04950738, 0.        ,
       0.07332356, 0.09365858, 0.        , 0.05270463, 0.11785113,
       0.        , 0.04811252, 0.05892557, 0.04003204, 0.10540926,
       0.        , 0.05892557, 0.        , 0.09901475, 0.13363062,
       0.08703883, 0.1132277 , 0.06154575, 0.        , 0.04564355,
       0.        , 0.05661385, 0.        , 0.        , 0.18463724,
       0.        , 0.15430335, 0.        , 0.09365858, 0.11785113,
       0.04811252, 0.03928371, 0.04351941, 0.        , 0.16984156,
       0.04256283, 0.04811252, 0.05892557, 0.        , 0.04256283,
       0.        , 0.0379049 , 0.        , 0.        , 0.04950738,
       0.10910895, 0.        , 0.10910895, 0.14048787, 0.        ,
       0.04564355, 0.        , 0.05103104, 0.05270463, 0.        ,
       0.07715167, 0.16984156, 0.12309149, 0.05661385, 0.06454972,
       0.03402069, 0.04166667, 0.05103104, 0.06454972, 0.09901475,
       0.08908708, 0.        , 0.        , 0.04811252, 0.08703883,
       0.08006408, 0.08512565, 0.        , 0.08333333, 0.        ,
       0.        , 0.04003204, 0.05103104, 0.05103104, 0.        ,
       0.05661385, 0.        , 0.10540926, 0.        , 0.        ,
       0.        , 0.        , 0.0372678 , 0.05103104, 0.        ,
       0.        , 0.03857584, 0.05103104, 0.12909944, 0.05892557,
       0.        , 0.0379049 , 0.05270463, 0.05103104, 0.        ,
       0.0372678 , 0.05270463, 0.12909944, 0.05892557, 0.04682929,
       0.        , 0.06804138, 0.        , 0.        , 0.        ,
       0.        , 0.13608276, 0.19364917, 0.10206207, 0.10540926,
       0.1132277 , 0.06154575, 0.24618298, 0.04950738, 0.        ,
       0.10206207, 0.06804138, 0.        , 0.08164966, 0.06804138,
       0.05103104, 0.        , 0.        , 0.09901475, 0.05661385,
       0.09365858, 0.18463724, 0.05892557, 0.10206207, 0.05661385,
       0.12309149, 0.08164966, 0.        , 0.09128709, 0.        ,
       0.11785113, 0.        , 0.        , 0.07216878, 0.        ,
       0.05661385, 0.12247449, 0.        , 0.14048787, 0.        ,
       0.10910895, 0.        , 0.09622504, 0.15309311, 0.        ,
       0.04454354, 0.11785113, 0.05892557, 0.11785113, 0.08703883,
       0.        , 0.        , 0.        , 0.13608276, 0.        ,
       0.        , 0.        , 0.        , 0.10910895, 0.        ,
       0.04950738, 0.        , 0.        , 0.04082483, 0.06454972,
       0.07216878, 0.1132277 , 0.        , 0.05270463, 0.06804138,
       0.1132277 , 0.09128709, 0.11785113, 0.        , 0.09622504,
       0.12909944, 0.05892557, 0.05103104, 0.22645541, 0.10910895,
       0.        , 0.1132277 , 0.14433757, 0.        , 0.05270463,
       0.        , 0.07856742, 0.        , 0.04351941, 0.04564355,
       0.05892557, 0.04950738, 0.        , 0.        , 0.        ,
       0.06804138, 0.05103104, 0.        , 0.06804138, 0.        ,
       0.08908708, 0.08703883, 0.        , 0.10540926, 0.10206207,
       0.05455447, 0.03928371, 0.14048787, 0.03928371, 0.05661385,
       0.        , 0.10206207, 0.10206207, 0.10540926, 0.04811252,
       0.06804138, 0.10910895, 0.04082483, 0.17025131, 0.06804138,
       0.        , 0.05455447, 0.13693064, 0.        , 0.10206207,
       0.05892557, 0.09128709, 0.04351941, 0.        , 0.0745356 ,
       0.11785113, 0.10206207, 0.10540926, 0.        , 0.        ,
       0.14433757, 0.04950738, 0.13608276, 0.        , 0.1132277 ,
       0.        , 0.        , 0.10540926, 0.        , 0.10540926,
       0.11785113, 0.05661385, 0.10910895, 0.04950738, 0.        ,
       0.06154575, 0.05270463, 0.03608439, 0.10660036, 0.        ,
       0.        , 0.05103104, 0.05455447, 0.06804138, 0.10910895,
       0.        , 0.        , 0.18463724, 0.        , 0.05892557,
       0.        , 0.04082483, 0.        , 0.        , 0.04256283,
       0.        , 0.04811252, 0.        , 0.        , 0.05661385,
       0.1132277 , 0.        , 0.        , 0.1132277 , 0.09901475,
       0.0758098 , 0.05661385, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05270463, 0.12247449,
       0.05892557, 0.        , 0.04564355, 0.04950738, 0.04454354,
       0.1132277 , 0.15309311, 0.        , 0.        , 0.12909944,
       0.10540926, 0.04811252, 0.        , 0.13608276, 0.        ,
       0.        , 0.04950738, 0.04003204, 0.        , 0.06804138,
       0.09901475, 0.05455447, 0.035007  , 0.15430335, 0.        ,
       0.05892557, 0.        , 0.        , 0.10206207, 0.        ,
       0.05892557, 0.05455447, 0.10910895, 0.        , 0.        ,
       0.04256283, 0.1132277 , 0.        , 0.        , 0.0372678 ,
       0.08512565, 0.        , 0.        , 0.04682929, 0.        ,
       0.05661385, 0.        , 0.03608439, 0.        , 0.05103104,
       0.05455447, 0.06804138, 0.        , 0.04166667, 0.        ,
       0.05455447, 0.09901475, 0.        , 0.        , 0.        ,
       0.20412415, 0.06804138, 0.        , 0.05661385, 0.05270463,
       0.        , 0.05661385, 0.05270463, 0.        , 0.04682929,
       0.        , 0.        , 0.        , 0.09622504, 0.        ,
       0.09622504, 0.11785113, 0.1132277 , 0.        , 0.05270463,
       0.05455447, 0.06154575, 0.08703883, 0.05892557, 0.06804138,
       0.03928371, 0.04950738, 0.05892557, 0.05661385, 0.08908708,
       0.12309149, 0.16366342, 0.06454972, 0.05103104, 0.        ,
       0.04166667, 0.        , 0.        , 0.06804138, 0.04950738,
       0.08703883, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05892557, 0.05103104, 0.        , 0.06154575,
       0.        , 0.        , 0.08512565, 0.09622504, 0.06804138,
       0.        , 0.        , 0.        , 0.12909944, 0.06804138,
       0.        , 0.07216878, 0.14852213, 0.04454354, 0.        ,
       0.        , 0.15811388, 0.05270463, 0.13608276, 0.18952451,
       0.14852213, 0.23145502, 0.05103104, 0.15811388, 0.        ,
       0.06154575, 0.10910895, 0.05270463, 0.        , 0.08703883,
       0.        , 0.        , 0.        , 0.        , 0.09622504,
       0.12309149, 0.        , 0.        , 0.04682929, 0.06154575,
       0.10540926, 0.        , 0.04682929, 0.10910895, 0.        ,
       0.04082483, 0.        , 0.03402069, 0.16329932, 0.06154575,
       0.        , 0.05455447, 0.        , 0.125     , 0.03928371,
       0.09901475, 0.03608439, 0.        , 0.04564355, 0.        ,
       0.        , 0.        , 0.10206207, 0.04564355, 0.        ,
       0.09901475, 0.13608276, 0.05892557, 0.09901475, 0.0758098 ,
       0.04950738, 0.1767767 , 0.        , 0.03857584, 0.        ,
       0.08908708, 0.05892557, 0.        , 0.        , 0.04351941,
       0.        , 0.        , 0.        , 0.16984156, 0.        ,
       0.10910895, 0.        , 0.        , 0.        , 0.04351941,
       0.        , 0.06154575, 0.        , 0.06804138, 0.14852213,
       0.        , 0.        , 0.        , 0.06454972, 0.08333333,
       0.        , 0.07715167, 0.        , 0.05270463, 0.12909944,
       0.13363062, 0.        , 0.        , 0.08908708, 0.        ,
       0.        , 0.        , 0.06804138, 0.05661385, 0.        ,
       0.06454972, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05270463, 0.12309149, 0.        ,
       0.        , 0.        , 0.06154575, 0.04454354, 0.1132277 ,
       0.06454972, 0.        , 0.        , 0.1132277 , 0.08908708,
       0.        , 0.06454972, 0.        , 0.05661385, 0.        ,
       0.        , 0.05892557, 0.        , 0.        , 0.        ,
       0.        , 0.11785113, 0.        , 0.        , 0.06454972,
       0.        , 0.        , 0.04564355, 0.        , 0.05892557,
       0.10910895, 0.        , 0.09128709, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05103104,
       0.05270463, 0.15309311, 0.0758098 , 0.10206207, 0.04564355,
       0.11785113, 0.        , 0.08512565, 0.        , 0.10910895,
       0.        , 0.04454354, 0.15811388, 0.        , 0.        ,
       0.03928371, 0.        , 0.        , 0.        , 0.        ,
       0.08512565, 0.07216878, 0.0379049 , 0.04166667, 0.        ,
       0.05661385, 0.05455447, 0.        , 0.        , 0.05455447,
       0.07216878, 0.08512565, 0.        , 0.05270463, 0.        ,
       0.        , 0.        , 0.08333333, 0.        , 0.07856742,
       0.        , 0.10206207, 0.10206207, 0.08908708, 0.04811252,
       0.        , 0.        , 0.10910895, 0.10206207, 0.1767767 ,
       0.05892557, 0.        , 0.08333333, 0.05270463, 0.        ,
       0.16984156, 0.09365858, 0.04950738, 0.        , 0.05892557,
       0.12309149, 0.        , 0.        , 0.12909944, 0.05892557,
       0.05661385, 0.05661385, 0.        , 0.        , 0.        ])

In [162]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])

[(0, np.float64(1.0000000000000002)),
 (47, np.float64(0.3849001794597506)),
 (61, np.float64(0.32025630761017426)),
 (83, np.float64(0.29095718698132317)),
 (94, np.float64(0.27216552697590873)),
 (260, np.float64(0.2581988897471611)),
 (466, np.float64(0.25660011963983365)),
 (4, np.float64(0.24618298195866542)),
 (322, np.float64(0.24195539543709926)),
 (17, np.float64(0.24077170617153845)),
 (661, np.float64(0.2405626121623441)),
 (931, np.float64(0.2405626121623441)),
 (41, np.float64(0.23338001400466835)),
 (81, np.float64(0.2333800140046683)),
 (168, np.float64(0.2333800140046683)),
 (490, np.float64(0.2321035412742638)),
 (507, np.float64(0.22680460581325726)),
 (539, np.float64(0.22680460581325726)),
 (495, np.float64(0.22222222222222227)),
 (108, np.float64(0.22075539284417395)),
 (71, np.float64(0.21821789023599236)),
 (786, np.float64(0.21821789023599236)),
 (838, np.float64(0.21821789023599236)),
 (85, np.float64(0.21516574145596762)),
 (206, np.float64(0.21516574145596762)),
 (278, np.float64(0.21516574145596762)),
 (36, np.float64(0.21350420507344953)),
 (50, np.float64(0.21350420507344953)),
 (102, np.float64(0.21350420507344953)),
 (371, np.float64(0.21350420507344953)),
 (51, np.float64(0.2057377999494559)),
 (182, np.float64(0.2057377999494559)),
 (184, np.float64(0.2057377999494559)),
 (187, np.float64(0.2057377999494559)),
 (228, np.float64(0.2057377999494559)),
 (939, np.float64(0.2057377999494559)),
 (193, np.float64(0.2041241452319315)),
 (74, np.float64(0.1987615979999813)),
 (942, np.float64(0.1987615979999813)),
 (238, np.float64(0.19641855032959654)),
 (582, np.float64(0.1924500897298753)),
 (7, np.float64(0.19245008972987526)),
 (32, np.float64(0.19245008972987526)),
 (577, np.float64(0.19245008972987526)),
 (972, np.float64(0.19245008972987526)),
 (91, np.float64(0.19245008972987523)),
 (715, np.float64(0.19245008972987523)),
 (14, np.float64(0.18670401120373464)),
 (72, np.float64(0.18670401120373464)),
 (84, np.float64(0.18670401120373464)),
 (111, np.float64(0.18670401120373464)),
 (126, np.float64(0.18670401120373464)),
 (232, np.float64(0.18670401120373464)),
 (754, np.float64(0.18670401120373464)),
 (777, np.float64(0.18670401120373464)),
 (859, np.float64(0.18670401120373464)),
 (305, np.float64(0.1851851851851852)),
 (131, np.float64(0.18257418583505539)),
 (315, np.float64(0.18257418583505539)),
 (457, np.float64(0.18257418583505539)),
 (467, np.float64(0.18257418583505539)),
 (773, np.float64(0.18257418583505539)),
 (10, np.float64(0.1814436846506058)),
 (26, np.float64(0.1814436846506058)),
 (46, np.float64(0.1814436846506058)),
 (52, np.float64(0.1814436846506058)),
 (799, np.float64(0.1814436846506058)),
 (266, np.float64(0.17660431427533915)),
 (56, np.float64(0.17407765595569785)),
 (67, np.float64(0.17407765595569785)),
 (86, np.float64(0.17407765595569785)),
 (379, np.float64(0.17407765595569785)),
 (412, np.float64(0.17407765595569785)),
 (472, np.float64(0.17407765595569785)),
 (486, np.float64(0.17407765595569785)),
 (627, np.float64(0.17407765595569785)),
 (814, np.float64(0.17407765595569785)),
 (19, np.float64(0.17213259316477408)),
 (127, np.float64(0.17213259316477408)),
 (587, np.float64(0.17213259316477408)),
 (31, np.float64(0.16798421022632323)),
 (129, np.float64(0.16798421022632323)),
 (150, np.float64(0.16798421022632323)),
 (160, np.float64(0.16798421022632323)),
 (166, np.float64(0.16798421022632323)),
 (169, np.float64(0.16798421022632323)),
 (300, np.float64(0.16798421022632323)),
 (342, np.float64(0.16798421022632323)),
 (778, np.float64(0.16798421022632323)),
 (870, np.float64(0.16798421022632323)),
 (973, np.float64(0.16798421022632323)),
 (157, np.float64(0.16666666666666669)),
 (294, np.float64(0.16666666666666669)),
 (304, np.float64(0.16666666666666669)),
 (362, np.float64(0.16666666666666669)),
 (487, np.float64(0.16666666666666669)),
 (511, np.float64(0.16666666666666669)),
 (541, np.float64(0.16666666666666669)),
 (836, np.float64(0.16666666666666669)),
 (935, np.float64(0.16666666666666669)),
 (151, np.float64(0.16412198797244362)),
 (158, np.float64(0.16412198797244362)),
 (207, np.float64(0.16412198797244362)),
 (172, np.float64(0.16051447078102563)),
 (18, np.float64(0.16012815380508716)),
 (70, np.float64(0.16012815380508716)),
 (97, np.float64(0.16012815380508716)),
 (121, np.float64(0.16012815380508716)),
 (203, np.float64(0.16012815380508716)),
 (208, np.float64(0.16012815380508716)),
 (224, np.float64(0.16012815380508716)),
 (233, np.float64(0.16012815380508716)),
 (241, np.float64(0.16012815380508716)),
 (292, np.float64(0.16012815380508716)),
 (311, np.float64(0.16012815380508716)),
 (389, np.float64(0.16012815380508716)),
 (413, np.float64(0.16012815380508716)),
 (535, np.float64(0.16012815380508716)),
 (543, np.float64(0.16012815380508716)),
 (643, np.float64(0.16012815380508716)),
 (660, np.float64(0.16012815380508716)),
 (732, np.float64(0.16012815380508716)),
 (898, np.float64(0.16012815380508716)),
 (28, np.float64(0.15713484026367724)),
 (79, np.float64(0.15430334996209194)),
 (295, np.float64(0.15430334996209194)),
 (373, np.float64(0.15430334996209194)),
 (400, np.float64(0.15430334996209194)),
 (505, np.float64(0.15430334996209194)),
 (581, np.float64(0.15430334996209194)),
 (612, np.float64(0.15430334996209194)),
 (624, np.float64(0.15430334996209194)),
 (746, np.float64(0.15430334996209194)),
 (791, np.float64(0.15430334996209194)),
 (920, np.float64(0.15430334996209194)),
 (977, np.float64(0.15430334996209194)),
 (149, np.float64(0.15396007178390023)),
 (491, np.float64(0.15396007178390023)),
 (501, np.float64(0.15396007178390023)),
 (654, np.float64(0.15396007178390023)),
 (813, np.float64(0.15396007178390023)),
 (33, np.float64(0.14907119849998599)),
 (38, np.float64(0.14907119849998599)),
 (132, np.float64(0.14907119849998599)),
 (249, np.float64(0.14907119849998599)),
 (307, np.float64(0.14907119849998599)),
 (607, np.float64(0.14907119849998599)),
 (665, np.float64(0.14907119849998599)),
 (781, np.float64(0.14907119849998599)),
 (55, np.float64(0.14814814814814817)),
 (740, np.float64(0.14814814814814817)),
 (381, np.float64(0.14547859349066158)),
 (678, np.float64(0.14547859349066158)),
 (9, np.float64(0.14433756729740643)),
 (35, np.float64(0.14433756729740643)),
 (37, np.float64(0.14433756729740643)),
 (39, np.float64(0.14433756729740643)),
 (122, np.float64(0.14433756729740643)),
 (190, np.float64(0.14433756729740643)),
 (332, np.float64(0.14433756729740643)),
 (508, np.float64(0.14433756729740643)),
 (589, np.float64(0.14433756729740643)),
 (978, np.float64(0.14433756729740643)),
 (16, np.float64(0.140028008402801)),
 (59, np.float64(0.140028008402801)),
 (96, np.float64(0.140028008402801)),
 (101, np.float64(0.140028008402801)),
 (368, np.float64(0.140028008402801)),
 (419, np.float64(0.140028008402801)),
 (483, np.float64(0.140028008402801)),
 (30, np.float64(0.13608276348795437)),
 (68, np.float64(0.13608276348795437)),
 (229, np.float64(0.13608276348795437)),
 (547, np.float64(0.13608276348795437)),
 (579, np.float64(0.13608276348795437)),
 (728, np.float64(0.13608276348795437)),
 (768, np.float64(0.13608276348795437)),
 (183, np.float64(0.13608276348795434)),
 (530, np.float64(0.13608276348795434)),
 (600, np.float64(0.13608276348795434)),
 (776, np.float64(0.13608276348795434)),
 (960, np.float64(0.13608276348795434)),
 (618, np.float64(0.13400504203456162)),
 (20, np.float64(0.13245323570650436)),
 (43, np.float64(0.13245323570650436)),
 (112, np.float64(0.13245323570650436)),
 (220, np.float64(0.13245323570650436)),
 (242, np.float64(0.13245323570650436)),
 (271, np.float64(0.13245323570650436)),
 (275, np.float64(0.13245323570650436)),
 (334, np.float64(0.13245323570650436)),
 (403, np.float64(0.13245323570650436)),
 (503, np.float64(0.13245323570650436)),
 (572, np.float64(0.13245323570650436)),
 (125, np.float64(0.1301200097264711)),
 (138, np.float64(0.12909944487358055)),
 (174, np.float64(0.12909944487358055)),
 (591, np.float64(0.12909944487358055)),
 (922, np.float64(0.12909944487358055)),
 (48, np.float64(0.12830005981991682)),
 (302, np.float64(0.12830005981991682)),
 (309, np.float64(0.12830005981991682)),
 (319, np.float64(0.12830005981991682)),
 (461, np.float64(0.12830005981991682)),
 (476, np.float64(0.12830005981991682)),
 (479, np.float64(0.12830005981991682)),
 (518, np.float64(0.12830005981991682)),
 (534, np.float64(0.12830005981991682)),
 (602, np.float64(0.12830005981991682)),
 (668, np.float64(0.12830005981991682)),
 (674, np.float64(0.12830005981991682)),
 (831, np.float64(0.12830005981991682)),
 (95, np.float64(0.12655439943366653)),
 (12, np.float64(0.12598815766974242)),
 (63, np.float64(0.12598815766974242)),
 (270, np.float64(0.12598815766974242)),
 (279, np.float64(0.12598815766974242)),
 (369, np.float64(0.12598815766974242)),
 (420, np.float64(0.12598815766974242)),
 (510, np.float64(0.12598815766974242)),
 (88, np.float64(0.12309149097933272)),
 (107, np.float64(0.12309149097933272)),
 (230, np.float64(0.12309149097933272)),
 (755, np.float64(0.12309149097933272)),
 (62, np.float64(0.12171612389003693)),
 (167, np.float64(0.12171612389003693)),
 (189, np.float64(0.12171612389003693)),
 (219, np.float64(0.12171612389003693)),
 (312, np.float64(0.12171612389003693)),
 (540, np.float64(0.12171612389003693)),
 (664, np.float64(0.12171612389003693)),
 (76, np.float64(0.12038585308576921)),
 (82, np.float64(0.12038585308576921)),
 (329, np.float64(0.12038585308576921)),
 (426, np.float64(0.12038585308576921)),
 (937, np.float64(0.12038585308576921)),
 (123, np.float64(0.11878277418329973)),
 (1, np.float64(0.11785113019775793)),
 (5, np.float64(0.11785113019775793)),
 (25, np.float64(0.11785113019775793)),
 (243, np.float64(0.11785113019775793)),
 (330, np.float64(0.11785113019775793)),
 (900, np.float64(0.11785113019775793)),
 (49, np.float64(0.1160517706371319)),
 (147, np.float64(0.1160517706371319)),
 (148, np.float64(0.1160517706371319)),
 (179, np.float64(0.1160517706371319)),
 (205, np.float64(0.1160517706371319)),
 (222, np.float64(0.1160517706371319)),
 (223, np.float64(0.1160517706371319)),
 (306, np.float64(0.1160517706371319)),
 (375, np.float64(0.1160517706371319)),
 (471, np.float64(0.1160517706371319)),
 (800, np.float64(0.1160517706371319)),
 (888, np.float64(0.1160517706371319)),
 (990, np.float64(0.1160517706371319)),
 (103, np.float64(0.11547005383792516)),
 (199, np.float64(0.11547005383792516)),
 (262, np.float64(0.11547005383792516)),
 (92, np.float64(0.11322770341445959)),
 (363, np.float64(0.11322770341445959)),
 (11, np.float64(0.11111111111111113)),
 (75, np.float64(0.11111111111111113)),
 (98, np.float64(0.11111111111111113)),
 (164, np.float64(0.11111111111111113)),
 (170, np.float64(0.11111111111111113)),
 (237, np.float64(0.11111111111111113)),
 (239, np.float64(0.11111111111111113)),
 (256, np.float64(0.11111111111111113)),
 (308, np.float64(0.11111111111111113)),
 (340, np.float64(0.11111111111111113)),
 (359, np.float64(0.11111111111111113)),
 (366, np.float64(0.11111111111111113)),
 (449, np.float64(0.11111111111111113)),
 (458, np.float64(0.11111111111111113)),
 (513, np.float64(0.11111111111111113)),
 (537, np.float64(0.11111111111111113)),
 (555, np.float64(0.11111111111111113)),
 (595, np.float64(0.11111111111111113)),
 (610, np.float64(0.11111111111111113)),
 (629, np.float64(0.11111111111111113)),
 (731, np.float64(0.11111111111111113)),
 (752, np.float64(0.11111111111111113)),
 (994, np.float64(0.11111111111111113)),
 (27, np.float64(0.10910894511799618)),
 (410, np.float64(0.10910894511799618)),
 (784, np.float64(0.10721125348377948)),
 (2, np.float64(0.10675210253672476)),
 (22, np.float64(0.10675210253672476)),
 (105, np.float64(0.10675210253672476)),
 (195, np.float64(0.10675210253672476)),
 (253, np.float64(0.10675210253672476)),
 (259, np.float64(0.10675210253672476)),
 (291, np.float64(0.10675210253672476)),
 (331, np.float64(0.10675210253672476)),
 (350, np.float64(0.10675210253672476)),
 (376, np.float64(0.10675210253672476)),
 (411, np.float64(0.10675210253672476)),
 (470, np.float64(0.10675210253672476)),
 (531, np.float64(0.10675210253672476)),
 (546, np.float64(0.10675210253672476)),
 (575, np.float64(0.10675210253672476)),
 (604, np.float64(0.10675210253672476)),
 (640, np.float64(0.10675210253672476)),
 (691, np.float64(0.10675210253672476)),
 (718, np.float64(0.10675210253672476)),
 (775, np.float64(0.10675210253672476)),
 (793, np.float64(0.10675210253672476)),
 (894, np.float64(0.10675210253672476)),
 (985, np.float64(0.10675210253672476)),
 (995, np.float64(0.10675210253672476)),
 (996, np.float64(0.10675210253672476)),
 (8, np.float64(0.10286889997472795)),
 (21, np.float64(0.10286889997472795)),
 (45, np.float64(0.10286889997472795)),
 (100, np.float64(0.10286889997472795)),
 (134, np.float64(0.10286889997472795)),
 (143, np.float64(0.10286889997472795)),
 (153, np.float64(0.10286889997472795)),
 (257, np.float64(0.10286889997472795)),
 (263, np.float64(0.10286889997472795)),
 (301, np.float64(0.10286889997472795)),
 (341, np.float64(0.10286889997472795)),
 (402, np.float64(0.10286889997472795)),
 (523, np.float64(0.10286889997472795)),
 (544, np.float64(0.10286889997472795)),
 (687, np.float64(0.10286889997472795)),
 (710, np.float64(0.10286889997472795)),
 (735, np.float64(0.10286889997472795)),
 (808, np.float64(0.10286889997472795)),
 (816, np.float64(0.10286889997472795)),
 (850, np.float64(0.10286889997472795)),
 (908, np.float64(0.10286889997472795)),
 (956, np.float64(0.10286889997472795)),
 (212, np.float64(0.10206207261596575)),
 (23, np.float64(0.09938079899999065)),
 (87, np.float64(0.09938079899999065)),
 (141, np.float64(0.09938079899999065)),
 (185, np.float64(0.09938079899999065)),
 (198, np.float64(0.09938079899999065)),
 (216, np.float64(0.09938079899999065)),
 (217, np.float64(0.09938079899999065)),
 (225, np.float64(0.09938079899999065)),
 (244, np.float64(0.09938079899999065)),
 (289, np.float64(0.09938079899999065)),
 (290, np.float64(0.09938079899999065)),
 (358, np.float64(0.09938079899999065)),
 (422, np.float64(0.09938079899999065)),
 (469, np.float64(0.09938079899999065)),
 (549, np.float64(0.09938079899999065)),
 (568, np.float64(0.09938079899999065)),
 (578, np.float64(0.09938079899999065)),
 (597, np.float64(0.09938079899999065)),
 (609, np.float64(0.09938079899999065)),
 (653, np.float64(0.09938079899999065)),
 (782, np.float64(0.09938079899999065)),
 (788, np.float64(0.09938079899999065)),
 (792, np.float64(0.09938079899999065)),
 (805, np.float64(0.09938079899999065)),
 (215, np.float64(0.09901475429766741)),
 (109, np.float64(0.09622504486493763)),
 (159, np.float64(0.09622504486493763)),
 (175, np.float64(0.09622504486493763)),
 (277, np.float64(0.09622504486493763)),
 (348, np.float64(0.09622504486493763)),
 (432, np.float64(0.09622504486493763)),
 (443, np.float64(0.09622504486493763)),
 (475, np.float64(0.09622504486493763)),
 (480, np.float64(0.09622504486493763)),
 (488, np.float64(0.09622504486493763)),
 (542, np.float64(0.09622504486493763)),
 (596, np.float64(0.09622504486493763)),
 (621, np.float64(0.09622504486493763)),
 (683, np.float64(0.09622504486493763)),
 (704, np.float64(0.09622504486493763)),
 (787, np.float64(0.09622504486493763)),
 (827, np.float64(0.09622504486493763)),
 (929, np.float64(0.09622504486493763)),
 (933, np.float64(0.09622504486493763)),
 (415, np.float64(0.09622504486493762)),
 (812, np.float64(0.09622504486493762)),
 (13, np.float64(0.09335200560186732)),
 (24, np.float64(0.09335200560186732)),
 (210, np.float64(0.09335200560186732)),
 (267, np.float64(0.09335200560186732)),
 (336, np.float64(0.09335200560186732)),
 (473, np.float64(0.09335200560186732)),
 (502, np.float64(0.09335200560186732)),
 (601, np.float64(0.09335200560186732)),
 (644, np.float64(0.09335200560186732)),
 (658, np.float64(0.09335200560186732)),
 (671, np.float64(0.09335200560186732)),
 (675, np.float64(0.09335200560186732)),
 (711, np.float64(0.09335200560186732)),
 (785, np.float64(0.09335200560186732)),
 (833, np.float64(0.09335200560186732)),
 (29, np.float64(0.0907218423253029)),
 (90, np.float64(0.0907218423253029)),
 (116, np.float64(0.0907218423253029)),
 (117, np.float64(0.0907218423253029)),
 (197, np.float64(0.0907218423253029)),
 (235, np.float64(0.0907218423253029)),
 (282, np.float64(0.0907218423253029)),
 (326, np.float64(0.0907218423253029)),
 (335, np.float64(0.0907218423253029)),
 (391, np.float64(0.0907218423253029)),
 (666, np.float64(0.0907218423253029)),
 (15, np.float64(0.08830215713766958)),
 (276, np.float64(0.08830215713766958)),
 (339, np.float64(0.08830215713766958)),
 (356, np.float64(0.08830215713766958)),
 (383, np.float64(0.08830215713766958)),
 (485, np.float64(0.08830215713766958)),
 (692, np.float64(0.08830215713766958)),
 (803, np.float64(0.08830215713766958)),
 (986, np.float64(0.08830215713766958)),
 (80, np.float64(0.08606629658238704)),
 (115, np.float64(0.08606629658238704)),
 (152, np.float64(0.08606629658238704)),
 (492, np.float64(0.08606629658238704)),
 (536, np.float64(0.08606629658238704)),
 (657, np.float64(0.08606629658238704)),
 (69, np.float64(0.08399210511316162)),
 (93, np.float64(0.08399210511316162)),
 (104, np.float64(0.08399210511316162)),
 (200, np.float64(0.08399210511316162)),
 (234, np.float64(0.08399210511316162)),
 (254, np.float64(0.08399210511316162)),
 (565, np.float64(0.08399210511316162)),
 (744, np.float64(0.08399210511316162)),
 (840, np.float64(0.08399210511316162)),
 (873, np.float64(0.08399210511316162)),
 (899, np.float64(0.08399210511316162)),
 (53, np.float64(0.08206099398622181)),
 (78, np.float64(0.08206099398622181)),
 (114, np.float64(0.08206099398622181)),
 (163, np.float64(0.08206099398622181)),
 (370, np.float64(0.08206099398622181)),
 (424, np.float64(0.08206099398622181)),
 (514, np.float64(0.08206099398622181)),
 (737, np.float64(0.08206099398622181)),
 (794, np.float64(0.08206099398622181)),
 (854, np.float64(0.08206099398622181)),
 (113, np.float64(0.08025723539051281)),
 (124, np.float64(0.08025723539051281)),
 (564, np.float64(0.08025723539051281)),
 (583, np.float64(0.08025723539051281)),
 (634, np.float64(0.08025723539051281)),
 (695, np.float64(0.08025723539051281)),
 (767, np.float64(0.08025723539051281)),
 (950, np.float64(0.08025723539051281)),
 (961, np.float64(0.08025723539051281)),
 (191, np.float64(0.07856742013183862)),
 (245, np.float64(0.07856742013183862)),
 (274, np.float64(0.07856742013183862)),
 (416, np.float64(0.07856742013183862)),
 (428, np.float64(0.07856742013183862)),
 (864, np.float64(0.07856742013183862)),
 (967, np.float64(0.07856742013183862)),
 (982, np.float64(0.07856742013183862)),
 (196, np.float64(0.07698003589195011)),
 (478, np.float64(0.07698003589195011)),
 (299, np.float64(0.07548513560963972)),
 (349, np.float64(0.07548513560963972)),
 (425, np.float64(0.07548513560963972)),
 (551, np.float64(0.07407407407407408)),
 (889, np.float64(0.07407407407407408)),
 (945, np.float64(0.07407407407407408)),
 (969, np.float64(0.07407407407407408)),
 (213, np.float64(0.07273929674533079)),
 (240, np.float64(0.07273929674533079)),
 (323, np.float64(0.07273929674533079)),
 (344, np.float64(0.07273929674533079)),
 (463, np.float64(0.07273929674533079)),
 (866, np.float64(0.07273929674533079)),
 (454, np.float64(0.07147416898918632)),
 (645, np.float64(0.07147416898918632)),
 (834, np.float64(0.07147416898918632)),
 (932, np.float64(0.07147416898918632)),
 (442, np.float64(0.07027283689263066)),
 (594, np.float64(0.07027283689263066)),
 (770, np.float64(0.07027283689263066)),
 (310, np.float64(0.06913011298202835)),
 (146, np.float64(0.06804138174397717)),
 (162, np.float64(0.06804138174397717)),
 (272, np.float64(0.06804138174397717)),
 (313, np.float64(0.06804138174397717)),
 (498, np.float64(0.06804138174397717)),
 (617, np.float64(0.06804138174397717)),
 (751, np.float64(0.06804138174397717)),
 (951, np.float64(0.06804138174397717)),

In [163]:
#lets create function when some give me movies we will find 5 similar movies
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x : x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [164]:
recommend('Superman')

Superman II
Superman Returns
Man of Steel
Batman v Superman: Dawn of Justice
Iron Man 2

In [165]:
import pickle
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [166]:
import pickle
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [167]:
#for get movies name
new_df.title.values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled',
       'Avengers: Age of Ultron',
       'Harry Potter and the Half-Blood Prince',
       'Batman v Superman: Dawn of Justice', 'Superman Returns',
       'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest",
       'The Lone Ranger', 'Man of Steel',
       'The Chronicles of Narnia: Prince Caspian', 'The Avengers',
       'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3',
       'The Hobbit: The Battle of the Five Armies',
       'The Amazing Spider-Man', 'Robin Hood',
       'The Hobbit: The Desolation of Smaug', 'The Golden Compass',
       'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship',
       'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3',
       'Alice in Wonderland', 'X-Men: The Last Stand',
       'Monsters University', 'Transformers: Revenge of the Fallen',
       'Transformers: Age of Extinction', 'Oz: The Great and Powerful',
       'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2',
       'Green Lantern', 'Toy Story 3', 'Terminator Salvation',
       'Furious 7', 'World War Z', 'X-Men: Days of Future Past',
       'Star Trek Into Darkness', 'Jack the Giant Slayer',
       'The Great Gatsby', 'Prince of Persia: The Sands of Time',
       'Pacific Rim', 'Transformers: Dark of the Moon',
       'Indiana Jones and the Kingdom of the Crystal Skull',
       'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E',
       'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending',
       'The Legend of Tarzan',
       'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
       'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens',
       'Iron Man', 'Hugo', 'Wild Wild West',
       'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad',
       'Evan Almighty', 'Edge of Tomorrow', 'Waterworld',
       'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book',
       'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent',
       'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin',
       'Captain America: The Winter Soldier', 'Shrek Forever After',
       'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph',
       'The Polar Express', 'Independence Day: Resurgence',
       'How to Train Your Dragon', 'Terminator 3: Rise of the Machines',
       'Guardians of the Galaxy', 'Interstellar', 'Inception',
       'Shin Godzilla', 'The Hobbit: An Unexpected Journey',
       'The Fast and the Furious', 'The Curious Case of Benjamin Button',
       'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2',
       "The Sorcerer's Apprentice", 'Poseidon',
       'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft',
       'Terminator Genisys',
       'The Chronicles of Narnia: The Voyage of the Dawn Treader',
       'Pearl Harbor', 'Transformers', 'Alexander',
       'Harry Potter and the Order of the Phoenix',
       'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend',
       'Charlie and the Chocolate Factory', 'Ratatouille',
       'Batman Begins', 'Madagascar: Escape 2 Africa',
       'Night at the Museum: Battle of the Smithsonian',
       'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen',
       'The Matrix Reloaded', 'Thor: The Dark World',
       'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force',
       'Wrath of the Titans', 'Dark Shadows',
       'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie',
       'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III',
       'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan',
       'Mr. Peabody & Sherman', 'Troy',
       "Madagascar 3: Europe's Most Wanted", 'Die Another Day',
       'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf',
       'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol',
       'Rise of the Guardians', 'Fun with Dick and Jane',
       'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek',
       'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt',
       'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk',
       'G.I. Joe: Retaliation', 'Sahara',
       'Final Fantasy: The Spirits Within',
       'Captain America: The First Avenger', 'The World Is Not Enough',
       'Master and Commander: The Far Side of the World',
       'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two',
       'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango',
       'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda',
       'Ant-Man', 'The Hunger Games: Catching Fire', 'Home',
       'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt',
       'Noah', 'The Adventures of Tintin',
       'Harry Potter and the Prisoner of Azkaban', 'Australia',
       'After Earth', 'Dinosaur',
       'Night at the Museum: Secret of the Tomb', 'Megamind',
       "Harry Potter and the Philosopher's Stone", 'R.I.P.D.',
       'Pirates of the Caribbean: The Curse of the Black Pearl',
       'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code',
       'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows',
       'Clash of the Titans', 'Total Recall', 'The 13th Warrior',
       'The Bourne Legacy', 'Batman & Robin',
       'How the Grinch Stole Christmas', 'The Day After Tomorrow',
       'Mission: Impossible II', 'The Perfect Storm',
       'Fantastic 4: Rise of the Silver Surfer', 'Life of Pi',
       'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle",
       'Prometheus', 'Stuart Little 2', 'Elysium',
       'The Chronicles of Riddick', 'RoboCop', 'Speed Racer',
       'How Do You Know', 'Knight and Day', 'Oblivion',
       'Star Wars: Episode III - Revenge of the Sith',
       'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.',
       'The Wolverine', 'Star Wars: Episode I - The Phantom Menace',
       'The Croods', 'Asterix at the Olympic Games', 'Windtalkers',
       "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles',
       'Gravity', "Dante's Peak",
       'Teenage Mutant Ninja Turtles: Out of the Shadows',
       'Fantastic Four', 'Night at the Museum', 'San Andreas',
       'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve",
       'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator',
       "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire',
       'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel',
       'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game",
       'Live Free or Die Hard',
       'The Lord of the Rings: The Fellowship of the Ring',
       'Around the World in 80 Days', 'Ali', 'The Cat in the Hat',
       'I, Robot', 'Kingdom of Heaven', 'Stuart Little',
       'The Princess and the Frog', 'The Martian', 'The Island',
       'Town & Country', 'Gone in Sixty Seconds', 'Gladiator',
       'Minority Report', 'Harry Potter and the Chamber of Secrets',
       'Casino Royale', 'Planet of the Apes',
       'Terminator 2: Judgment Day', 'Public Enemies',
       'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3',
       'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained',
       'The Hunchback of Notre Dame', "The Emperor's New Groove",
       'The Expendables 2', 'National Treasure', 'Eragon',
       'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days',
       'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever',
       'Starship Troopers', 'Cloud Atlas',
       "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman',
       'Hercules', 'Treasure Planet', 'Land of the Lost',
       'The Expendables 3', 'Point Break', 'Son of the Mask',
       'In the Heart of the Sea', 'The Adventures of Pluto Nash',
       'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner',
       'The Mummy Returns', 'Gangs of New York', 'The Flowers of War',
       "Surf's Up", 'The Stepford Wives', 'Black Hawk Down',
       'The Campaign', 'The Fifth Element', 'Sex and the City 2',
       'The Road to El Dorado', 'Ice Age: Continental Drift',
       'Cinderella', 'The Lovely Bones', 'Finding Nemo',
       'The Lord of the Rings: The Return of the King',
       'The Lord of the Rings: The Two Towers', 'Seventh Son',
       'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III',
       'Rise of the Planet of the Apes', 'The Spiderwick Chronicles',
       'A Good Day to Die Hard', 'The Alamo', 'The Incredibles',
       'Cutthroat Island',
       'Percy Jackson & the Olympians: The Lightning Thief',
       'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2',
       'What Lies Beneath', 'Cloudy with a Chance of Meatballs',
       'Ice Age: Dawn of the Dinosaurs',
       'The Secret Life of Walter Mitty', "Charlie's Angels",
       'The Departed', 'Mulan', 'Tropic Thunder',
       'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance',
       'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire',
       'Alvin and the Chipmunks: The Road Chip', 'Valkyrie',
       "You Don't Mess with the Zohan", 'Pixels',
       'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact',
       'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters',
       'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2',
       'The Saint', 'Spy Game', 'Mission to Mars', 'Rio',
       'Bicentennial Man', 'Volcano', "The Devil's Own",
       'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man',
       'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister',
       'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One',
       "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania',
       'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist',
       'The Holiday', 'Enemy of the State', "It's Complicated",
       "Ocean's Thirteen", 'Open Season', 'Divergent',
       'Enemy at the Gates', 'The Rundown', 'Last Action Hero',
       'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift',
       'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage',
       'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World',
       'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo',
       'Dredd', 'Click', 'Creepshow',
       'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper',
       'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day',
       'Bruce Almighty', 'The Expendables', 'Mission: Impossible',
       'The Hunger Games', 'The Hangover Part II', 'Batman Returns',
       'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web",
       'Deep Impact', 'RED 2', 'The Longest Yard',
       'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart',
       "Something's Gotta Give", 'Shutter Island', 'Four Christmases',
       'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition',
       'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain',
       'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam',
       'The Pink Panther', 'The Day the Earth Stood Still',
       'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear',
       'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space',
       'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2',
       'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young',
       'Swordfish', 'The Legend of Zorro', 'What Dreams May Come',
       'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Evolution',
       'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight',
       'Walking With Dinosaurs', 'Battlefield Earth',
       'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman',
       'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet',
       'Arthur and the Invisibles', 'Oceans', 'A Sound of Thunder',
       'Pompeii', 'Top Cat Begins', 'A Beautiful Mind', 'The Lion King',
       'Journey 2: The Mysterious Island',
       'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo',
       'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince',
       'The Invasion', 'The Adventures of Rocky & Bullwinkle',
       'The Secret Life of Pets', 'The League of Extraordinary Gentlemen',
       'Despicable Me 2', 'Independence Day',
       'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men',
       'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown',
       '50 First Dates', 'Hairspray', 'Exorcist: The Beginning',
       'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal',
       'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War",
       'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich',
       'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.',
       'Spanglish', 'Monster House', 'Bandits', 'First Knight',
       'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.',
       'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone',
       'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch',
       'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold",
       'Funny People', 'The Kingdom',
       'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2',
       'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic',
       'Driven', 'Two Brothers', 'The Village', 'Doctor Dolittle',
       'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx',
       'The SpongeBob Movie: Sponge Out of Water', 'Ransom',
       'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.',
       'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator',
       'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers',
       'Olympus Has Fallen', 'Star Trek: Insurrection',
       'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse',
       'The Monuments Men', 'The Abyss',
       'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege',
       'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company',
       'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages',
       "Hart's War", 'Killer Elite', 'Rollerball',
       'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones',
       "Legends of Oz: Dorothy's Return", 'Blackhat',
       'Sky Captain and the World of Tomorrow', 'Basic Instinct 2',
       'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears',
       'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me',
       'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass',
       'The Insider', 'The Finest Hours', 'Body of Lies',
       'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter',
       'Entrapment', 'The X Files', 'The Last Legion',
       'Saving Private Ryan', 'Need for Speed', 'What Women Want',
       'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13',
       'The Santa Clause 2', 'Les Misérables', "You've Got Mail",
       'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken',
       'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid',
       'World Trade Center', 'Mona Lisa Smile', 'The Dictator',
       'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War',
       'Blade: Trinity', 'Red Dawn', 'Primary Colors',
       'Resident Evil: Retribution', 'Death Race',
       'The Long Kiss Goodnight', 'Proof of Life',
       'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall',
       'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist',
       'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts',
       'Everest', 'Perfume: The Story of a Murderer',
       'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park',
       'Wyatt Earp', 'Clear and Present Danger', 'Dragon Blade',
       'Little Man', 'U-571', 'The American President', 'The Love Guru',
       '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory',
       'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile',
       'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity',
       'GoldenEye', "The General's Daughter", 'The Truman Show',
       'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs',
       'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat',
       'Days of Thunder', 'Cheaper by the Dozen 2',
       'Maze Runner: The Scorch Trials', 'Eat Pray Love',
       'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer',
       'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher',
       'Deep Blue Sea', 'This Is It', 'Contagion', 'Kangaroo Jack',
       'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog',
       'Starsky & Hutch', 'Jingle All the Way', 'Hellboy',
       'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck',
       'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo',
       'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit',
       'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter',
       'The Boxtrolls', 'Practical Magic', 'The Lego Movie',
       'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire',
       'Gangster Squad', 'Year One', 'Invictus', 'State of Play',
       'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51',
       'Star Trek: Nemesis', 'Intolerable Cruelty',
       'Trouble with the Curve', 'Edge of Darkness', 'The Relic',
       'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist',
       'The Legend of Bagger Vance', 'Almost Famous',
       'Garfield: A Tail of Two Kitties', 'xXx: State of the Union',
       'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon',
       'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle',
       'Supernova', "Winter's Tale",
       'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water',
       'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai',
       'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders',
       'The Monkey King 2', 'The Great Raid', 'Deadpool', 'Holy Man',
       'American Sniper', 'Goosebumps', 'Just Like Heaven',
       'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads',
       'The Ridiculous 6', 'Did You Hear About the Morgans?',
       'The Internship', 'Resident Evil: Afterlife', 'Red Tails',
       "The Devil's Advocate", "That's My Boy", 'DragonHeart',
       'After the Sunset', 'Ghost Rider: Spirit of Vengeance',
       "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall',
       'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents',
       'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch',
       'George of the Jungle', 'American Wedding', 'Captain Phillips',
       'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan',
       'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan',
       'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger',
       'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her',
       'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins",
       'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin',
       'The Ghost and the Darkness', 'Paddington', 'The Watch',
       'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro',
       'The Pirates! In an Adventure with Scientists!', 'Changeling',
       'Chain Reaction', 'The Fan', 'The Phantom of the Opera',
       'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals',
       'Turbulence', 'Imagine That', 'Muppets Most Wanted',
       'Thunderbirds', 'Burlesque', 'A Very Long Engagement', 'Lolita',
       'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head',
       'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree',
       'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia',
       'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass',
       'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse',
       'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty',
       'The Break-Up', 'Mamma Mia!', "Valentine's Day",